project:
  group: laplacian
  name: model.project-template
  type: template
  namespace: laplacian
  version: '1.0.0'
  description:
    en: |
      The model.project-template project.
    ja: |
      The model.project-template project.
    zh: |
      The model.project-template project.
  source_repository:
    url: https://github.com/laplacian-core/model.project-template.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
#  template_files:
#  - 'dest/template'
